# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_dirichlet_mom <- function(Y) {
    .Call(`_DirichletRF_estimate_dirichlet_mom`, Y)
}

estimate_dirichlet_mle <- function(Y, max_iter = 10000L, tol = 1e-6, lambda = 1e-6) {
    .Call(`_DirichletRF_estimate_dirichlet_mle`, Y, max_iter, tol, lambda)
}

DirichletForest <- function(X, Y, B = 100L, d_max = 10L, n_min = 5L, m_try = -1L, seed = 123L, method = "mom", store_samples = FALSE, num_cores = 1L) {
    .Call(`_DirichletRF_DirichletForest`, X, Y, B, d_max, n_min, m_try, seed, method, store_samples, num_cores)
}

GetLeafPredictions <- function(forest_model, X_new) {
    .Call(`_DirichletRF_GetLeafPredictions`, forest_model, X_new)
}

PredictDirichletForestWeightBased <- function(forest_model, X_new, method = "mom") {
    .Call(`_DirichletRF_PredictDirichletForestWeightBased`, forest_model, X_new, method)
}

PredictDirichletForest <- function(forest_model, X_new, method = "mom", use_leaf_predictions = TRUE) {
    .Call(`_DirichletRF_PredictDirichletForest`, forest_model, X_new, method, use_leaf_predictions)
}

GetSampleWeights <- function(forest_model, test_sample) {
    .Call(`_DirichletRF_GetSampleWeights`, forest_model, test_sample)
}

